### ISSUE TITLE
switching to a new watch face and then coming back freezes the watch 

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/Time-To-Learn#18]
could be related to a missing internet connection? 

i think it's something else. 
i do have a connection, and other watch faces are updating info from the net, so it can't be this.

**Comment by yarchiT** [comment]
can you please describe a little bit more about the problem or maybe upload the video? cause what i tested in emulator i coudnt find any bug.

**Comment by mircealungu** [comment]
this is how it looks: 

   https://www.dropbox.com/s/14vri0d0tn2xrzf/VID_20170613_094534.mp4?dl=0

cna you replicate this in the emulator?

**Comment by Robin1711** [comment]
Hello Mircea,

I don't know if this is a mistake from our side. Of what I find on the internet is that it also could have to do with an update with a mistake in it.
Have you by any chance updated something on the watch?

We have a new version in the context branch. Do you have time to deploy that one? In that version we solved all the other issues and maybe an issue that could have to do with this, but we're not sure, since testing is impossible.
If, after deployment of the new version, the problem still occurs, could you try closing all the apps. And if that does not work restarting the watch?

If the problem still occurs we have more information on what the problem could be, so if you are able to do this, it would be great.

Thanks in advance,
Regards,
Robin

**Comment by mircealungu** [comment]
Robin,

I just deployed the version from the context branch.
It's quite stable, that's cool. 

Now the watch face does not freeze when i switch to another one and back so that's cool... but it invites me to select a language. This is not the desired behavior. Note that in the previous version,  once I've logged in I was be able to change watch faces and come back without the need to login again. 

Please check your code changes around the login screen and make sure that you check for the existence of user data in the local storage. If you find user data, then load the user info from the local storage rather than trying to create a new account.  (Or maybe you're not creating a new account, only that you didn't take into consideration the situation where the language might already be in the settings and thus you don't have to present the language selection screen?)

But otherwise cool stuff!

**Comment by Robin1711** [comment]
We will look into this!

**Comment by Robin1711** [comment]
We fixed it. The relogin works now.

**Comment by mircealungu** [comment]
Nice!
